#!/usr/bin/env bash
set -e

VERSION="1.0.0"
NAME="Aiterra-v${VERSION}"
SRC="crypto-ai-trader"
OUT="${NAME}.zip"

echo "Building ${OUT}..."

rm -rf "/tmp/${NAME}" "${OUT}"
mkdir -p "/tmp/${NAME}"

# Copy using Python (no rsync needed)
python3 - <<'PYEOF'
import shutil, os

src = "crypto-ai-trader"
dst = f"/tmp/Aiterra-v1.0.0"

EXCLUDE_DIRS  = {"venv", "__pycache__", "dist", "build", "backend", "mobile", ".git"}
EXCLUDE_FILES = {".env", "docker-compose.yml", "CHECK.bat", "SETUP.bat",
                 "CREATE_SHORTCUT.bat", "trades.db", "make_release.sh",
                 "settings.yml"}  # user config — regenerated by INSTALL.bat
EXCLUDE_EXT   = {".pyc", ".pyo", ".pyd", ".bak"}

def should_skip(name, is_dir):
    if is_dir  and name in EXCLUDE_DIRS:  return True
    if not is_dir and name in EXCLUDE_FILES: return True
    if not is_dir and os.path.splitext(name)[1] in EXCLUDE_EXT: return True
    return False

for root, dirs, files in os.walk(src):
    dirs[:] = [d for d in dirs if not should_skip(d, True)]
    rel = os.path.relpath(root, src)
    dest_dir = os.path.join(dst, rel)
    os.makedirs(dest_dir, exist_ok=True)
    for f in files:
        if not should_skip(f, False):
            shutil.copy2(os.path.join(root, f), os.path.join(dest_dir, f))

# Ensure empty dirs
for d in ["data", "models"]:
    os.makedirs(os.path.join(dst, d), exist_ok=True)
    open(os.path.join(dst, d, ".gitkeep"), "w").close()

print("  Files staged OK")
PYEOF

# Create zip
cd /tmp
zip -rq "${OLDPWD}/${OUT}" "${NAME}/" \
    -x "*/.DS_Store" "*/Thumbs.db" "*/__pycache__/*"

echo "Done: ${OUT}  ($(du -sh "${OLDPWD}/${OUT}" | cut -f1))"
